# Generated by Django 4.1.6 on 2023-02-01 15:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="added_on",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 1, 21, 14, 33, 750524)
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
