# Generated by Django 4.1.6 on 2023-02-01 16:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manga", "0002_alter_manga_added_on_alter_manga_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manga",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="manga",
            name="added_on",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 1, 22, 10, 32, 964516)
            ),
        ),
    ]
